Estuve jugando con `manage.py`, `settings.py` para configurar el servidor de acuerdo a una variable de ambiente `DJANGO_ENV` para poder decidir dinámicamente si quiero ejecutar el servidor de desarrollo de Django o probar con el servidor en producción `Gunicorn` que será el que terminaremos usando cuando despleguemos la aplicación. (Queda pendiente configurarlo con Nginx, que aunque no haga falta para nuestro trabajo, es una buena oportunidad para aprender).
Ahora, teniendo just instalado, podemos hacer:
- just serve dev
- just serve prod

Para los servidores de desarrollo y producción, respectivamente.

diff --git a/server/src/Justfile b/server/src/Justfile
--- a/server/src/Justfile
+++ b/server/src/Justfile
@@ -1,22 +1,23 @@
-venv:
-    source .venv/bin/activate.fish
+# https://github.com/casey/just
 
-serve:
-    uv run ruff format ./
+serve mode="dev": migrate
+    #!/usr/bin/env bash
+    set -euxo pipefail
+    if [ "{{mode}}" = "dev" ]; then \
+        DJANGO_ENV={{mode}} uv run manage.py runserver  
+    elif [ "{{mode}}" = "prod" ]; then \
+        DJANGO_ENV={{mode}} uv run gunicorn --workers 3 --log-level info --access-logfile '-' --error-logfile '-' backend.wsgi:application 
+    fi
+    
+migrate: fmt
     uv run ./manage.py makemigrations
     uv run ./manage.py migrate
-    uv run ./manage.py runserver
 
-migrate:
-    uv run ./manage.py makemigrations
-    uv run ./manage.py migrate
-
-test:
-    uv run ./manage.py migrate
-    uv run ./manage.py test
-
-check:
+check: fmt
     ruff check ./
+
+test: migrate check fmt
+    uv run ./manage.py test
 
 fmt:
     ruff format ./
